### ISSUE TITLE
Returning Any from function declared to return "Optional[InsertOneResult]"

### ISSUE THREAD

**Issue by oiwn** [mongodb-labs/pymongo-stubs#13]
Hello!

I can't figure out why insert_one return Any instead of certain pymongo result type

```Returning Any from function declared to return "Optional[InsertOneResult]"```

Minimum example:

```python
from typing import Dict, Optional

import pymongo


def store_to_mongo(
    mongo_client: pymongo.MongoClient, data: Dict
) -> Optional[pymongo.results.InsertOneResult]:
    """Reproduce typing warning"""
    if data:
        return mongo_client["temp"].insert_one(data)  # <<-- Returning Any from function declared...
    return None
```

Versions

```
Python 3.9.6
pymongo-stubs      0.1.0
mypy               0.910
mypy-extensions    0.4.3
```

**Comment by ShaneHarvey** [comment]
The problem looks like a bug in your code:
```python
return mongo_client["temp"].insert_one(data)
```

This line attempts to call insert_one() on the "temp" Database but this method only exists on Collections. What happens when you change the line to:
```python
return mongo_client["temp_db"]["temp_coll"].insert_one(data)
```

**Comment by oiwn** [comment]
> The problem looks like a bug in your code:
> 
> ```python
> return mongo_client["temp"].insert_one(data)
> ```
> 
> This line attempts to call insert_one() on the "temp" Database but this method only exists on Collections. What happens when you change the line to:
> 
> ```python
> return mongo_client["temp_db"]["temp_coll"].insert_one(data)
> ```

I got it! The code is correct, type annotation is not, i already passing mongo_client as  ```mongo_client = pymongo.MongoClient(URI).get_database()``` so instead of ```mongo_client: pymongo.MongoClient``` i should use ```mongo_client: pymongo.database.Database```

**Comment by ShaneHarvey** [comment]
> i should use: mongo_client: pymongo.database.Database

I'd suggest renaming the `mongo_client` variable to `db` or something else since `client` usually refers to a MongoClient.

Okay to close this issue?

**Comment by oiwn** [comment]
> > i should use: mongo_client: pymongo.database.Database
> 
> I'd suggest renaming the `mongo_client` variable to `db` or something else since `client` usually refers to a MongoClient.
> 
> Okay to close this issue?

yea, can close.
